# This is a basic workflow to help you get started with Actions

name: Superuser

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: archcraft

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: jiro4989/setup-nim-action@v2.0.2
      - name: Setup Nim environment
        # You may pin to the exact commit or the version.
        # uses: jiro4989/setup-nim-action@5bbc93d889ba575ed95cde254faa197193690456
        with:
          # The Nim version to download (if necessary) and use. Example: 1.0.2
          nim-version: 2.0.2
                
